#!/bin/sh
# The certificate is generated by the novnc-certs service in docker-compose,
# the same one-shot alpine pattern pg-certs uses for timescaledb. Failing
# loudly here beats quietly serving something unencrypted: noVNC's RA2ne path
# needs window.crypto.subtle, which browsers only expose in a secure context.
set -eu

PEM="${NOVNC_CERT:-/certs/novnc.pem}"

if [ ! -f "$PEM" ]; then
    echo "novnc: no certificate at $PEM." >&2
    echo "novnc: the novnc-certs service should have written one." >&2
    exit 1
fi

exec websockify \
    --web /opt/novnc \
    --cert "$PEM" \
    "0.0.0.0:${NOVNC_PORT:-6080}" \
    "${NOVNC_TARGET:-weston:5900}"
