# build and push dbus-session image to docker hub

name: Build and Push Dbus Session Docker Image

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    paths:
      - 'dbus-session/**'
      - '.github/workflows/dbus-session.yml'

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./dbus-session
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/dbus-session:${{ github.sha }},ghcr.io/${{ github.repository_owner }}/dbus-session:latest
