name: Publish Data Logger as Docker Image

on:
  workflow_dispatch:  # Manual trigger

permissions:
  contents: write
  packages: write

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout blossom repository
        uses: actions/checkout@v4
        with:
          repository: centroid-is/blossom
          token: ${{ secrets.GH_PAT }}
          path: blossom
          ref: add_brim_logger

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true

      - name: Get version from Cargo.toml
        id: cargo_version
        working-directory: blossom/brim_data_logger
        run: |
          # Extract the version from Cargo.toml (expects a line like: version = "1.2.3")
          VERSION=$(sed -n 's/^version\s*=\s*"\(.*\)"/\1/p' Cargo.toml | head -n1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Found Cargo.toml version: $VERSION"

      - name: Build artifact
        working-directory: blossom/brim_data_logger
        run: |
          cargo build --release --target x86_64-unknown-linux-musl

      - name: Prepare Docker build context
        working-directory: blossom/brim_data_logger
        run: |
          # Create a Dockerfile that copies the built binary into an Alpine-based image.
          # Adjust the binary name if it differs from 'brim-data-logger'
          cat <<'EOF' > Dockerfile
          FROM alpine:latest
          COPY target/x86_64-unknown-linux-musl/release/brim_data_logger /usr/local/bin/brim_data_logger
          RUN chmod +x /usr/local/bin/brim_data_logger
          ENTRYPOINT ["/usr/local/bin/brim_data_logger"]
          EOF

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: blossom/brim_data_logger
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/brim-data-logger:${{ steps.cargo_version.outputs.version }},ghcr.io/${{ github.repository_owner }}/brim-data-logger:latest
