name: Build and Push sv-hmi Docker Image

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  elinux-build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/centroid-is/tfc-toolchain:latest
    outputs:
      sildarvinnsla_sha: ${{ steps.get_sha.outputs.sha }}
    steps:
      - name: Vulnarable
        run: git config --system --add safe.directory '*'
      - name: Checkout sildarvinnsla
        uses: actions/checkout@v4
        with:
          repository: centroid-is/sildarvinnsla
          token: ${{ secrets.GH_PAT }}
          path: sildarvinnsla
          ref: master

      - name: Get commit SHA
        id: get_sha
        working-directory: sildarvinnsla
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Setup elinux platform
        working-directory: sildarvinnsla/hmi
        run: flutter-elinux create --platforms=elinux .

      - name: Get Flutter Packages
        working-directory: sildarvinnsla/hmi
        run: flutter-elinux pub get

      - name: Build for eLinux
        working-directory: sildarvinnsla/hmi
        run: flutter-elinux build elinux --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sildarvinnsla-artifacts
          path: |
            sildarvinnsla/hmi/build/elinux/x64/release/bundle/sildarvinnsla
            sildarvinnsla/hmi/build/elinux/x64/release/bundle/lib/libflutter_engine.so
            sildarvinnsla/hmi/build/elinux/x64/release/bundle/lib/libflutter_elinux_wayland.so

  docker-build:
    needs: elinux-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Docker repo
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: sildarvinnsla-artifacts
          path: artifacts

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: flutter
          push: true
          build-args: |
            APP_BIN=artifacts/sildarvinnsla
            FLUTTER_ENGINE=artifacts/libflutter_engine.so
            FLUTTER_ELINUX_WAYLAND=artifacts/libflutter_elinux_wayland.so
          tags: |
            ghcr.io/${{ github.repository_owner }}/sv-hmi:${{ needs.elinux-build.outputs.sildarvinnsla_sha }}
            ghcr.io/${{ github.repository_owner }}/sv-hmi:latest
